### ISSUE TITLE
Why does zipkin lose so much data with high concurrency?

### ISSUE THREAD

**Issue by HefeiJoe** [Kong/kong-plugin-zipkin#47]
Concurrent 400,Loop 10 times
Jmeter:
![image](https://user-images.githubusercontent.com/27885579/63510033-29073e80-c510-11e9-9d53-aa9abbd22d20.png)

ES:
![image](https://user-images.githubusercontent.com/27885579/63510075-3de3d200-c510-11e9-9f27-9f4f904596a8.png)

**Comment by adriancole** [comment]
probably this is on the wrong repo. you can chat here https://gitter.im/openzipkin/zipkin

also you can look at STORAGE_THROTTLE_ENABLED 
https://github.com/openzipkin/zipkin/tree/master/zipkin-server#throttled-storage-experimental

at the end of the day you will see drop metrics if you overwhelm elasticsearch (pretty easy to do on laptop). STORAGE_THROTTLE_ENABLED tries to respond to errors from elasticsearch and backup accordingly. The best way is actually to use a queue/topic like kafka instead of http when using an underprovisioned elasticsearch.

hope this helps.

**Comment by HefeiJoe** [comment]
> probably this is on the wrong repo. you can chat here https://gitter.im/openzipkin/zipkin
> 
> also you can look at STORAGE_THROTTLE_ENABLED
> https://github.com/openzipkin/zipkin/tree/master/zipkin-server#throttled-storage-experimental
> 
> at the end of the day you will see drop metrics if you overwhelm elasticsearch (pretty easy to do on laptop). STORAGE_THROTTLE_ENABLED tries to respond to errors from elasticsearch and backup accordingly. The best way is actually to use a queue/topic like kafka instead of http when using an underprovisioned elasticsearch.
> 
> hope this helps.

Yes, I've set STORAGE_TYPE before, but it doesn't solve the problem of lost data.
Then I thought about whether I could get kong's data through kafka. I set the environment variable KAFKA_BOOTSTRAP_SERVERS of zipkin, but felt no improvement.I guess kong's data is still sent over HTTP
![image](https://user-images.githubusercontent.com/27885579/63559905-63132780-c586-11e9-9936-6531a6099d99.png)

**Comment by adriancole** [comment]
> Yes, I've set STORAGE_TYPE before, but it doesn't solve the problem of
> lost data.
> Then I thought about whether I could get kong's data through kafka. I set
> the environment variable KAFKA_BOOTSTRAP_SERVERS of zipkin, but felt no
> improvement.I guess kong's data is still sent over HTTP
>

zipkin can receive from many transports at the same time. I don't think
kong has an option besides http right now.

https://github.com/Kong/kong-plugin-zipkin/blob/master/kong/plugins/zipkin/reporter.lua

It does seem to have some means to sample. Also, as mentioned, you can
enable storage throttling which will reduce impact of a lot of things
thrashing at the same time.

Also, someone can check how flushing works here.. usually we bundle many
spans together and flush on occasion. ES is known to have problems when a
whole bunch of things write at the same time. If flushing mechanisms here
can result in that, this could be an issue also. Also remember the "flush
concern" applies to not just here but anything you have sending data. Kafka
fixes this problem because it decouples reporting of data and how parallel
that is from writes to ES.
